version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zoo1
    ports:
      - '2181:2181'
    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: 'Topic1:3:2,Topic2:2:2'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/data/kafka:/kafka'
    depends_on:
      - zookeeper
    restart: always
